---
- name: run Update Systems
  hosts: Systems
  roles:
   - Update

- name: run katello-tracer-upload
  hosts: Sat6Clients
  roles:
   - Tracer

- name: run insights-client
  hosts: Systems
  roles:
   - Insights

- name: run update RHV hypervisors
  hosts: RHEV
  roles:
   - UpdateRHV

- name: run clean logs
  hosts: all
  roles:
   - CleanUpLogs
