---
- name: Dec 2021:  Update Systems
  hosts: Systems
  roles:
   - Update

- name: Dec 2021:  katello-tracer-upload
  hosts: Sat6Clients
  roles:
   - Tracer

- name: Dec 2021:  insights-client
  hosts: Systems
  roles:
   - Insights

- name: Dec 2021:  update RHV hypervisors
  hosts: RHEV
  roles:
   - UpdateRHV

- name: Dec 2021: clean logs
  hosts: all
  roles:
   - CleanUpLogs
