---
- name: Update Systems
  hosts: Systems
  roles:
   - Update

- name: katello-tracer-upload
  hosts: Sat6Clients
  roles:
   - Tracer

- name: insights-client
  hosts: Systems
  roles:
   - Insights

- name: update RHV hypervisors
  hosts: RHEV
  roles:
   - UpdateRHV

- name: clean logs
  hosts: all
  roles:
   - CleanUpLogs
